import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Plus, Trash2, Send, Sparkles, Film, Paperclip, ArrowRight, Download, Loader2, StickyNote, Upload, Undo2, Redo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useChatThreads, cryptoId, type ChatMessage, type ChatAttachment, type ChatThread } from "@/lib/storage";
import { cn } from "@/lib/utils";
import { VideoUploader, type UploadedFile } from "@/components/chat/VideoUploader";
import { InteractiveThinkingPanel } from "@/components/chat/InteractiveThinkingPanel";
import type { ThinkingStage } from "@/components/chat/ThinkingPanel";
import { BlueprintPreview } from "@/components/chat/BlueprintPreview";
import { VideoPreview } from "@/components/chat/VideoPreview";
import { TextTimeline } from "@/components/chat/TextTimeline";
import { AnalysisPanel } from "@/components/chat/AnalysisPanel";
import { CreativeBriefPanel } from "@/components/chat/CreativeBriefPanel";
import { uploadFileDirect, transcribeMedia, analyzeReferenceStyle, analyzeReferenceStyleByUrl, persistStudioProject } from "@/lib/api-client";
import { runGenerationPipeline, refineProject, exportProject, type PipelineStage } from "../../apps/web/src/lib/kove-generation-pipeline";
import type { ReferenceStyle } from "@/server/types/reference-style";
import type { TimelineAnnotation } from "@/server/types/annotation";
import { type ExportProgress } from "@/lib/export-engine";
import type { MonetEDL, Shot } from "@/server/types/edl";
import type { TranscriptResult } from "@/server/api/transcribe";
import { addDemoTrackedTextOverlay } from "@/lib/openreel/motion-tracking";
import { addAutoFaceTrack } from "@/lib/openreel/face-tracking";
import { addDemoPlanarTextOverlay } from "@/lib/openreel/planar-tracking";
import { useProjectStore } from "../../apps/web/src/stores/project-store";
import { registerMonetExecutor } from "../../apps/web/src/lib/executors/monet-action-executor";
import { syncUploadedFilesAndEDLToProject } from "../../apps/web/src/lib/media/project-media-hydration";
import { probeVideoClientSide } from "@/lib/client-probe";
import { scoreSimilarity } from "../lib/style/reference-similarity";
import { routeEDL, summarizeRouting } from "../lib/engines/router";

const ENABLE_HYPERFRAMES = false;

registerMonetExecutor(useProjectStore);




function formatApiError(error: any): string {
  if (!error) return "";
  if (typeof error === "string") return error;
  if (typeof error === "object") {
    if (typeof error.message === "string") return error.message;
    if (typeof error.error === "object" && typeof error.error.message === "string") return error.error.message;
    return JSON.stringify(error);
  }
  return String(error);
}

type ThinkingData = {
  intentConfidence?: number;
  edlShots?: number;
  scores?: {
    beatSyncScore: number;
    pacingVariance: number;
    overallConfidence: number;
  };
  usedFallback?: boolean;
  error?: string;
  edl?: MonetEDL;
  creativeDensity?: any;
  styleDirectives?: any;
  referenceSimilarity?: any;
};

// @ts-expect-error - Route tree auto-generated by TanStack Router; not yet typed at this import location
export const Route = createFileRoute("/chat_/$threadId")({
  component: ChatPage,
});

function ChatPage() {
  const { threadId } = Route.useParams();
  const navigate = Route.useNavigate();
  const { threads, hydrated, createThread, deleteThread, updateThread } = useChatThreads();
  const [draft, setDraft] = useState("");
  const [uploadedFiles, setUploadedFiles] = useState<UploadedFile[]>([]);
  const [thinkingStage, setThinkingStage] = useState<ThinkingStage>("idle");
  const [refineFeedback, setRefineFeedback] = useState("");
  const [isRefining, setIsRefining] = useState(false);
  /** Time-anchored annotations added by pausing the preview */
  const [annotations, setAnnotations] = useState<TimelineAnnotation[]>([]);
  const abortRef = useRef<AbortController | null>(null);
  const taRef = useRef<HTMLTextAreaElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  const chatFileInputRef = useRef<HTMLInputElement>(null);
  /** Track reference file ids already analyzed so type-toggle reruns analysis */
  const analyzedRefIds = useRef<Set<string>>(new Set());

  const [transcript, setTranscript] = useState<TranscriptResult | null>(null);
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [showTextTimeline, setShowTextTimeline] = useState(false);
  const [isAnalyzingReference, setIsAnalyzingReference] = useState(false);
  const [analysisData, setAnalysisData] = useState<any>(null);
  const [creativeBrief, setCreativeBrief] = useState<any>(null);
  const [thinkingThoughts, setThinkingThoughts] = useState<any[]>([]);
  const [thinkingQuestions, setThinkingQuestions] = useState<any[]>([]);
  const [previewTimeMs, setPreviewTimeMs] = useState(0);
  const [seekToMs, setSeekToMs] = useState<number | undefined>(undefined);
  const [isAutoTrackingFace, setIsAutoTrackingFace] = useState(false);
  const [compositionHtml, setCompositionHtml] = useState<string | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState<ExportProgress | null>(null);

  // --- Zustand canonical state (MUST be before derived state) ---
  const currentEDL = useProjectStore((s) => s.generation.edl) as any as MonetEDL | null;
  const currentEdlId = useProjectStore((s) => s.generation.edlId) ?? null;
  const currentIntentId = useProjectStore((s) => s.prompt.intentId) ?? null;
  const currentAnalysisId = useProjectStore((s) => s.analysis.analysisId) ?? null;
  const generationStatus = useProjectStore((s) => s.generation.status);
  const isGenerating = generationStatus === "generating";
  const editIntensity = useProjectStore((s) => s.prompt.intensity) ?? 0.5;
  const tempoMode = useProjectStore((s) => s.prompt.tempoMode) ?? "beat_anticipated";
  const referenceStyle = useProjectStore((s) => {
    const edl = s.generation.edl as any;
    return edl?.referenceStyle ?? (s.project?.settings as any)?.monet?.referenceStyle ?? null;
  });
  const currentIntent = useProjectStore((s) => s.prompt.intent);
  const directorMessages = useProjectStore((s) => s.director.messages);
  const setPrompt = useProjectStore((s) => s.setPrompt);
  const setGeneration = useProjectStore((s) => s.setGeneration);
  const setAnalysis = useProjectStore((s) => s.setAnalysis);
  const setAssets = useProjectStore((s) => s.setAssets);
  const setTruth = useProjectStore((s) => s.setTruth);

  // --- Derived state ---
  const generationScores = useProjectStore((s) => s.generation.scores);
  const generationFallback = useProjectStore((s) => s.generation.fallbackUsed);
  const thinkingData = useMemo(() => ({
    edlShots: currentEDL?.shots?.length ?? 0,
    scores: generationScores,
    usedFallback: generationFallback,
    edl: currentEDL,
    error: generationStatus === "failed" ? "Generation failed" : undefined,
    intentConfidence: (currentIntent as any)?.confidence,
  }), [currentEDL, generationScores, generationFallback, generationStatus, currentIntent]);

  // Derive mediaUrls from Zustand assets + EDL
  const mediaUrls = useMemo(() => {
    const urls = new Map<string, string>();
    const assets = useProjectStore.getState().assets;

    // Map all assets from Zustand store (authoritative source)
    for (const f of assets.footage) {
      if (f.r2FileId) {
        urls.set(f.r2FileId, `/api/media/${f.r2FileId}`);
        // Also map the asset ID (may differ from r2FileId)
        if (f.id !== f.r2FileId) urls.set(f.id, `/api/media/${f.r2FileId}`);
      }
    }
    if (assets.music?.r2FileId) {
      urls.set(assets.music.r2FileId, `/api/media/${assets.music.r2FileId}`);
      if (assets.music.id !== assets.music.r2FileId) urls.set(assets.music.id, `/api/media/${assets.music.r2FileId}`);
    }
    if (assets.reference?.r2FileId) {
      urls.set(assets.reference.r2FileId, `/api/media/${assets.reference.r2FileId}`);
    }

    // Also build mapping from local UploadedFile IDs → R2 IDs
    for (const uf of uploadedFiles) {
      if (uf.r2FileId) {
        urls.set(uf.id, `/api/media/${uf.r2FileId}`);
        urls.set(`dev-${uf.file.name}`, `/api/media/${uf.r2FileId}`);
      } else if (uf.preview) {
        // Not yet uploaded — use blob URL as temporary fallback
        urls.set(uf.id, uf.preview);
      }
    }

    // Map EDL shots — ensure every clipId resolves to a URL
    if (currentEDL) {
      for (const shot of currentEDL.shots) {
        const clipId = shot.source.clipId;
        if (!urls.has(clipId)) {
          // Try to find by matching against known IDs
          let resolved = false;
          for (const [key, url] of urls) {
            if (clipId.includes(key) || key.includes(clipId)) {
              urls.set(clipId, url);
              resolved = true;
              break;
            }
          }
          if (!resolved) {
            // Last resort: use server URL with the clipId
            urls.set(clipId, `/api/media/${encodeURIComponent(clipId)}_proxy`);
          }
        }
      }
      if (currentEDL.music?.sourceId && !urls.has(currentEDL.music.sourceId)) {
        urls.set(currentEDL.music.sourceId, `/api/media/${encodeURIComponent(currentEDL.music.sourceId)}`);
      }
    }

    return urls;
  }, [currentEDL, uploadedFiles]);

  // Derive engine routing from EDL
  const engineRouting = useMemo(() => {
    if (!currentEDL) return null;
    try {
      const routing = routeEDL(currentEDL, { tier: "free" });
      return summarizeRouting(routing);
    } catch {
      return null;
    }
  }, [currentEDL]);

  // After EDL is generated or restored, compute and log similarity scores
  useEffect(() => {
    if (!currentEDL) return;
    scoreSimilarity(currentEDL as any, referenceStyle);
  }, [currentEDL, referenceStyle]);
  const [directorJobId, setDirectorJobId] = useState<string | null>(null);
  const [directorRenderStatus, setDirectorRenderStatus] = useState<string | null>(null);
  const [directorPreviewUrl, setDirectorPreviewUrl] = useState<string | null>(null);
  const [patchSummary, setPatchSummary] = useState<string | null>(null);
  const lastPersistedStudioSnapshotRef = useRef<string | null>(null);
  const chatUiStorageKey = `monet.chat.ui.${threadId}`;

  const resolveMediaKeys = (file: UploadedFile): string[] => {
    const keys = [file.id, `dev-${file.file.name}`, file.file.name];

    if (file.r2FileId) {
      keys.push(file.r2FileId);
    }

    return Array.from(new Set(keys.filter(Boolean)));
  };

  const active = (threads as ChatThread[]).find((t) => t.id === threadId);

  const resolvableMediaIds = useMemo(() => {
    const ids = new Set<string>();

    for (const file of uploadedFiles) {
      if (file.type !== "footage" && file.type !== "music") continue;
      for (const key of resolveMediaKeys(file)) ids.add(key);
    }

    for (const message of active?.messages ?? []) {
      for (const attachment of message.attachments ?? []) {
        const canonical = attachment.r2FileId ?? attachment.id;
        if (!canonical) continue;
        ids.add(canonical);
        if (attachment.id) ids.add(attachment.id);
        if (attachment.name) ids.add(`dev-${attachment.name}`);
      }
    }

    return ids;
  }, [uploadedFiles, active?.messages]);

  const canResolvePreviewClip = (clipId: string): boolean => {
    return mediaUrls.has(clipId) || resolvableMediaIds.has(clipId);
  };

  const missingPreviewClips: string[] = currentEDL
    ? Array.from(
        new Set(
          currentEDL.shots
            .map((shot: Shot) => shot.source.clipId)
            .filter((clipId: string) => !canResolvePreviewClip(clipId))
        )
      )
    : [];

  const mediaApiBase =
    ((import.meta as any).env?.VITE_API_BASE ||
      (typeof window !== "undefined" ? window.location.origin : ""))
      .replace(/\/$/, "");

  const buildMediaUrl = (mediaId: string) =>
    mediaApiBase
      ? `${mediaApiBase}/api/media/${encodeURIComponent(mediaId)}`
      : `/api/media/${encodeURIComponent(mediaId)}`;

  const buildPreviewMediaUrl = (mediaId: string) => {
    if (mediaId.endsWith("_proxy")) return buildMediaUrl(mediaId);
    return buildMediaUrl(`${mediaId}_proxy`);
  };

  useEffect(() => {
    if (!hydrated) return;
    if (!active && threads.length > 0) {
      navigate({ to: "/chat/$threadId", params: { threadId: threads[0].id }, replace: true } as any);
    } else if (!active && threads.length === 0) {
      const t = createThread();
      navigate({ to: "/chat/$threadId", params: { threadId: t.id }, replace: true } as any);
    }
  }, [hydrated, active, threads, navigate, createThread]);

  useEffect(() => {
    taRef.current?.focus();
  }, [threadId]);

  // New thread = new session. Clear transient state when switching chats.
  useEffect(() => {
    abortRef.current?.abort();
    setDraft("");
    setUploadedFiles([]);
    setThinkingStage("idle");
    setRefineFeedback("");
    setIsRefining(false);
    setAnnotations([]);
    setTranscript(null);
    setIsTranscribing(false);
    setShowTextTimeline(false);
    setIsAnalyzingReference(false);
    setCompositionHtml(null);
    setDirectorJobId(null);
    setDirectorRenderStatus(null);
    setDirectorPreviewUrl(null);
    setPatchSummary(null);
    analyzedRefIds.current.clear();
    // Reset Zustand canonical state
    useProjectStore.getState().resetProjectContext();
  }, [threadId]);

  // Restore EDL from persisted thread state when switching threads or on refresh
  useEffect(() => {
    if (!active) return;
    const latestEdl = active.latestEdl ? (active.latestEdl as any) : null;
    if (latestEdl) {
      setGeneration({ edl: latestEdl, edlId: active.latestEdlId ?? undefined, status: "ready" });
    }
    if (active.latestIntentId) setPrompt({ intentId: active.latestIntentId });
    if (active.latestAnalysisId) setAnalysis({ analysisId: active.latestAnalysisId });

    const latestRef = active.latestReferenceStyle
      ? (active.latestReferenceStyle as ReferenceStyle)
      : null;

    // Auto-wire ReferenceStyle into Project Store settings
    const project = useProjectStore.getState().project;
    if (project && latestRef) {
      const updatedProject = {
        ...project,
        settings: {
          ...project.settings,
          monet: {
            ...(project.settings?.monet || {}),
            referenceStyle: latestRef,
            referenceStyleId: (active as any).latestReferenceStyleId || undefined
          }
        }
      };
      useProjectStore.setState({ project: updatedProject });
    }
  }, [threadId, active]);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [active?.messages.length]);

  // mediaUrls is now derived via useMemo above

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(chatUiStorageKey);
      if (!raw) return;
      const parsed = JSON.parse(raw) as {
        showTextTimeline?: boolean;
        refineFeedback?: string;
        annotations?: TimelineAnnotation[];
      };
      if (typeof parsed.showTextTimeline === "boolean") {
        setShowTextTimeline(parsed.showTextTimeline);
      }
      if (typeof parsed.refineFeedback === "string") {
        setRefineFeedback(parsed.refineFeedback);
      }
      if (Array.isArray(parsed.annotations)) {
        setAnnotations(parsed.annotations);
      }
    } catch {
      // Ignore corrupt local UI state and fall back to defaults.
    }
  }, [chatUiStorageKey]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      window.localStorage.setItem(
        chatUiStorageKey,
        JSON.stringify({
          showTextTimeline,
          refineFeedback,
          annotations,
        })
      );
    } catch {
      // UI persistence is best-effort only.
    }
  }, [chatUiStorageKey, showTextTimeline, refineFeedback, annotations]);

  useEffect(() => {
    if (!currentEDL || !active) return;
    const snapshotKey = `${threadId}:${currentEdlId ?? "no-edl-id"}:${currentEDL.timeline.duration}:${currentEDL.shots.length}`;
    if (lastPersistedStudioSnapshotRef.current === snapshotKey) return;

    lastPersistedStudioSnapshotRef.current = snapshotKey;
    persistStudioProject(
      {
        projectId: threadId,
        threadId,
        projectName: active.title,
        edlId: currentEdlId ?? undefined,
        edl: currentEDL,
      },
      abortRef.current?.signal ?? undefined
    ).catch((err: any) => {
      console.warn("Failed to persist studio snapshot:", err);
    });
  }, [active, threadId, currentEDL, currentEdlId]);

  const previewShotCount = currentEDL?.shots.length ?? 0;
  const previewDuration = currentEDL?.timeline.duration ?? 0;
  const previewClipCount = currentEDL
    ? new Set(currentEDL.shots.map((shot: Shot) => shot.source.clipId)).size
    : 0;
  const previewReady = currentEDL != null && mediaUrls.size > 0 && missingPreviewClips.length === 0;

  const handleFilesChange = async (files: UploadedFile[]) => {
    setUploadedFiles(files);

    // Eagerly analyze any reference file not yet analyzed
    const newRef = files.find(
      (f: UploadedFile) => f.type === "reference" && !analyzedRefIds.current.has(f.id)
    );
    if (!newRef || isAnalyzingReference) return;
    analyzedRefIds.current.add(newRef.id);

    setIsAnalyzingReference(true);
    try {
     let fileId = newRef.r2FileId;
     if (!fileId) {
       let metadata;
       try {
         if (newRef.file.type.startsWith("video/")) {
           metadata = await probeVideoClientSide(newRef.file);
         }
       } catch (probeErr) {
         console.warn("Reference probe failed", probeErr);
       }

       const uploadRes = await uploadFileDirect(newRef.file, threadId, "reference", metadata);        if (!uploadRes.success) throw new Error(formatApiError(uploadRes.error) || "Reference upload failed");
        fileId = uploadRes.fileId;
        setUploadedFiles((prev: UploadedFile[]) =>
          prev.map((f) => (f.id === newRef.id ? { ...f, r2FileId: fileId } : f))
        );
      }
      const styleRes = await analyzeReferenceStyle(threadId, fileId);
      if (styleRes.success && styleRes.style) {
        updateThread(threadId, (t: ChatThread) => ({
          ...t,
          updatedAt: Date.now(),
          latestReferenceStyle: styleRes.style,
          latestReferenceStyleId: styleRes.referenceStyleId,
          latestReferenceTrace: (styleRes as any).trace,
        }));

        // Sync reference style into Zustand store
        const project = useProjectStore.getState().project;
        if (project) {
          const updatedProject = {
            ...project,
            settings: {
              ...project.settings,
              monet: {
                ...(project.settings?.monet || {}),
                referenceStyle: styleRes.style,
                referenceStyleId: styleRes.referenceStyleId
              }
            }
          };
          useProjectStore.setState({ project: updatedProject });
        }
      } else {
        console.warn("Reference analysis returned no style:", styleRes.error);
        analyzedRefIds.current.delete(newRef.id); // allow retry
      }
    } catch (err: any) {
      console.error("Reference analysis failed:", err);
      analyzedRefIds.current.delete(newRef.id);
    } finally {
      setIsAnalyzingReference(false);
    }
  };

  /** Called by VideoUploader when user submits a YouTube / direct URL */
  const handleYouTubeUrl = async (url: string) => {
    if (!url || isAnalyzingReference) return;
    setIsAnalyzingReference(true);
    try {
      const styleRes = await analyzeReferenceStyleByUrl(threadId, url);
      if (styleRes.success && styleRes.style) {
        updateThread(threadId, (t: ChatThread) => ({
          ...t,
          updatedAt: Date.now(),
          latestReferenceStyle: styleRes.style,
          latestReferenceStyleId: styleRes.referenceStyleId,
          latestReferenceTrace: (styleRes as any).trace,
        }));

        // Sync reference style into Zustand store
        const project = useProjectStore.getState().project;
        if (project) {
          const updatedProject = {
            ...project,
            settings: {
              ...project.settings,
              monet: {
                ...(project.settings?.monet || {}),
                referenceStyle: styleRes.style,
                referenceStyleId: styleRes.referenceStyleId
              }
            }
          };
          useProjectStore.setState({ project: updatedProject });
        }
      } else {
        console.warn("YouTube reference analysis returned no style:", styleRes.error);
      }
    } catch (err: any) {
      console.error("YouTube reference analysis failed:", err);
    } finally {
      setIsAnalyzingReference(false);
    }
  };

  const applyGeneratedEDLToProject = async (
    generatedEdl: MonetEDL,
    currentFiles: UploadedFile[]
  ) => {
    const store = useProjectStore.getState();
    const project = store.project ?? store.bootstrapEmptyProject();

    const syncedProject = syncUploadedFilesAndEDLToProject({
      project,
      uploadedFiles: currentFiles,
      edl: generatedEdl,
      buildMediaUrl,
    });

    useProjectStore.setState({ project: syncedProject });

    // Build mediaUrlMap from uploaded files (r2FileId → blob URL) for the store
    const mediaUrlMap: Record<string, string> = {};
    for (const f of currentFiles) {
      if (f.r2FileId && (f.type === "footage" || f.type === "music")) {
        mediaUrlMap[f.r2FileId] = URL.createObjectURL(f.file);
      }
    }

    const applyResult = await useProjectStore.getState().applyMonetEDLToProject(
      generatedEdl,
      undefined,
      mediaUrlMap
    );

    if (!applyResult.success) {
      throw new Error(
        formatApiError(applyResult.error) ||
          "Failed to apply Monet EDL to project tracks"
      );
    }
  };

  const sendMessage = async (overrideText?: string | React.MouseEvent) => {
    const text = (typeof overrideText === "string" ? overrideText : draft).trim();
    if (!text || !active || isGenerating) return;

    const messageAttachments: ChatAttachment[] = uploadedFiles.map((file: UploadedFile) => ({
      id: file.id,
      type: file.type,
      name: file.file.name,
      sizeBytes: file.file.size,
      r2FileId: file.r2FileId,
    }));

    // Add user message
    const userMsg: ChatMessage = {
      id: cryptoId(),
      role: "user",
      content: text,
      createdAt: Date.now(),
      attachments: messageAttachments.length > 0 ? messageAttachments : undefined,
    };

    updateThread(threadId, (t: ChatThread) => ({
      ...t,
      title: t.messages.length === 0 ? text.slice(0, 40) : t.title,
      updatedAt: Date.now(),
      messages: [...t.messages, userMsg],
    }));

    setDraft("");
    setGeneration({ status: "generating" });

    try {
      setThinkingStage("intent");
      const abort = new AbortController();
      abortRef.current = abort;

      // Use shared pipeline for generation
      const pipelineResult = await runGenerationPipeline({
        projectId: threadId,
        files: uploadedFiles.map((f) => ({ file: f.file, type: f.type as any })),
        prompt: text,
        intensity: editIntensity,
        tempoMode,
        referenceMode: referenceStyle ? "strict_replication" : "inspired",
        signal: abort.signal,
        onStageChange: (stage: PipelineStage) => {
          if (stage === "uploading") setThinkingStage("intent");
          else if (stage === "analyzing") setThinkingStage("analysis");
          else if (stage === "generating") setThinkingStage("edl");
          else if (stage === "ready") setThinkingStage("complete");
          else if (stage === "error") setThinkingStage("error");
        },
      });

      if (!pipelineResult.success || !pipelineResult.edl) {
        throw new Error(pipelineResult.error || "Generation failed");
      }

      // Update uploadedFiles with R2 IDs from pipeline
      if (pipelineResult.mediaUrlMap) {
        setUploadedFiles((prev) =>
          prev.map((f) => {
            // Check if this file's name or ID appears in the mediaUrlMap keys
            for (const key of Object.keys(pipelineResult.mediaUrlMap)) {
              if (key === f.id || key === f.file.name || key === `dev-${f.file.name}`) {
                return { ...f, r2FileId: key };
              }
            }
            return f;
          })
        );
      }

      const generatedEDL = pipelineResult.edl as MonetEDL;

      // Apply EDL to Zustand store
      await applyGeneratedEDLToProject(generatedEDL, uploadedFiles);

      setThinkingStage("complete");

      // Persist EDL in thread for Studio import
      updateThread(threadId, (t: ChatThread) => ({
        ...t,
        updatedAt: Date.now(),
        latestEdl: generatedEDL,
        latestEdlId: pipelineResult.edlId,
        projectId: threadId,
      }));

      // Add assistant response
      const shots = generatedEDL.shots?.length ?? 0;
      const duration = generatedEDL.timeline?.duration ?? 30;
      const avgShot = shots > 0 ? (duration / shots).toFixed(1) : "0";
      const beatSync = pipelineResult.scores?.beatSyncScore != null
        ? Math.round(pipelineResult.scores.beatSyncScore * 100)
        : 0;

      let message = `✨ Edit complete!\n\n`;
      message += `📊 ${shots} shots, ${duration}s total (${avgShot}s avg)\n`;
      message += `🎵 Beat sync: ${beatSync}%\n`;
      if (pipelineResult.fallbackUsed) message += `\n⚠️ Generated with deterministic fallback (LLM busy)`;
      message += `\n\nReady to preview and refine!`;

      const assistantMsg: ChatMessage = {
        id: cryptoId(),
        role: "assistant",
        content: message,
        createdAt: Date.now(),
      };

      updateThread(threadId, (t: ChatThread) => ({
        ...t,
        updatedAt: Date.now(),
        messages: [...t.messages, assistantMsg],
      }));
    } catch (error: any) {
      console.error("Generation error:", error);
      setGeneration({ status: "failed" });
      setThinkingStage("error");

      const errorMsg: ChatMessage = {
        id: cryptoId(),
        role: "assistant",
        content: `Sorry, I encountered an error: ${error instanceof Error ? error.message : "Unknown error"}. Please try again.`,
        createdAt: Date.now(),
      };

      updateThread(threadId, (t: ChatThread) => ({
        ...t,
        updatedAt: Date.now(),
        messages: [...t.messages, errorMsg],
      }));
    } finally {
      abortRef.current = null;
      setTimeout(() => {
        setThinkingStage((s: ThinkingStage) => (s === "error" ? "idle" : s));
      }, 3000);
    }
  };

  function generateSuccessMessage(edlRes: { edl?: MonetEDL; scores?: { beatSyncScore: number }; usedFallback?: boolean }): string {
    const shots = edlRes.edl?.shots?.length ?? 0;
    const duration = edlRes.edl?.timeline?.duration ?? 30;
    const avgShot = shots > 0 ? (duration / shots).toFixed(1) : "0";
    const beatSync = edlRes.scores?.beatSyncScore != null
      ? Math.round(edlRes.scores.beatSyncScore * 100)
      : 0;

    let message = `✨ Edit complete!\n\n`;
    message += `📊 ${shots} shots, ${duration}s total (${avgShot}s avg)\n`;
    message += `🎵 Beat sync: ${beatSync}%\n`;
    if (edlRes.usedFallback) message += `\n⚠️ Generated with deterministic fallback (LLM busy)`;
    message += `\n\nReady to preview and refine!`;
    return message;
  }

  const handleDirectorFeedback = async (feedback: string) => {
    if (!feedback || isRefining) return;
    setIsRefining(true);
    setDirectorJobId(null);
    setDirectorRenderStatus(null);
    setDirectorPreviewUrl(null);
    setPatchSummary(null);

    try {
      // Use shared refineProject orchestrator
      const result = await refineProject({
        projectId: threadId,
        prompt: feedback,
        mode: "auto",
      });

      if (!result.success) {
        if (result.error?.includes("No EDL")) {
          // If no EDL, route to full generation
          await sendMessage(feedback);
          return;
        }
        throw new Error(result.error || "Director feedback failed");
      }

      // Apply refined EDL to store
      if (result.edl) {
        await applyGeneratedEDLToProject(result.edl as MonetEDL, uploadedFiles);
        updateThread(threadId, (t: ChatThread) => ({
          ...t,
          latestEdl: result.edl,
          updatedAt: Date.now(),
        }));
      }

      setPatchSummary(result.patchSummary ?? "Applying changes...");

      // Add assistant message for feedback
      const msg: ChatMessage = {
        id: cryptoId(),
        role: "assistant",
        content: `🎬 Director: "${feedback}"\n${result.patchSummary}`,
        createdAt: Date.now(),
      };
      updateThread(threadId, (t: ChatThread) => ({
        ...t,
        messages: [...t.messages, msg],
      }));

    } catch (err: any) {
      console.error("Director loop error:", err);
    } finally {
      setIsRefining(false);
    }
  };

  const handleRefine = async () => {
    const feedback = refineFeedback.trim();
    if (!feedback || isRefining) return;
    
    // Redirect refine to Director loop if EDL exists
    if (currentEDL) {
      setRefineFeedback("");
      await handleDirectorFeedback(feedback);
      return;
    }

    setIsRefining(true);
    setRefineFeedback("");
    try {
      // Use shared refineProject orchestrator
      const result = await refineProject({
        projectId: threadId,
        prompt: feedback,
        mode: "full-edl",
      });

      if (!result.success) throw new Error(result.error || "Refinement failed");

      // Apply refined EDL to store
      if (result.edl) {
        await applyGeneratedEDLToProject(result.edl as MonetEDL, uploadedFiles);
        updateThread(threadId, (t: ChatThread) => ({
          ...t,
          updatedAt: Date.now(),
          latestEdl: result.edl,
        }));
      }

      const msg: ChatMessage = {
        id: cryptoId(),
        role: "assistant",
        content: `✏️ Refined! "${feedback}"\n${(result.edl as any)?.shots?.length ?? 0} shots · ${((result.edl as any)?.timeline?.duration ?? 0).toFixed(1)}s`,
        createdAt: Date.now(),
      };
      updateThread(threadId, (t: ChatThread) => ({
        ...t,
        messages: [...t.messages, msg],
      }));
    } catch (err: any) {
      console.error("Refinement error:", err);
    } finally {
      setIsRefining(false);
    }
  };

  const handleExport = async () => {
    if (!currentEDL || isExporting) return;
    setIsExporting(true);
    setExportProgress(null);

    try {
      setExportProgress({ percent: 0, stage: "Preparing assets..." } as any);

      // Use shared exportProject orchestrator
      const result = await exportProject({
        projectId: threadId,
        preferServer: true,
        onProgress: (p) => {
          setExportProgress({ ...p, stage: p.stage } as any);
        },
      });

      if (!result.success || !result.blob) {
        throw new Error(result.error || "Export failed");
      }

      // Download
      const url = URL.createObjectURL(result.blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `monet-edit-${Date.now()}.mp4`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 5000);
    } catch (err: any) {
      console.error("Export error:", err);
      console.error("Export failed:", err.message || "Unknown error", "\nMake sure FFmpeg is installed and the dev server is running.");
    } finally {
      setIsExporting(false);
      setExportProgress(null);
    }
  };

  const handleTranscribe = async () => {
    const footageFile = uploadedFiles.find((f: UploadedFile) => f.type === "footage");
    if (!footageFile || isTranscribing) return;
    setIsTranscribing(true);
    try {
      const mediaId = footageFile.r2FileId ?? `dev-${footageFile.file.name}`;
      const res = await transcribeMedia(threadId, mediaId, "footage");
      if (res.success && res.result) {
        setTranscript({
          mediaId: res.result.mediaId,
          words: res.result.words,
          fullText: res.result.full_text,
          duration_ms: res.result.duration_ms,
          language: "en",
        } satisfies TranscriptResult);
        setShowTextTimeline(true);
      }
    } catch (err: any) {
      console.error("Transcription error:", err);
    } finally {
      setIsTranscribing(false);
    }
  };

  const handleOpenInStudio = () => {
    if (currentEDL) {
      updateThread(threadId, (t: ChatThread) => ({ ...t, latestEdl: currentEDL, latestEdlId: currentEdlId ?? undefined }));
    }
    window.location.assign(`/studio?threadId=${encodeURIComponent(threadId)}`);
  };

  const handleAddTrackedText = () => {
    if (!currentEDL) return;
    const updated = addDemoTrackedTextOverlay(currentEDL, "TRACKED TITLE");
    setGeneration({ edl: updated as any });
    updateThread(threadId, (t: ChatThread) => ({
      ...t,
      updatedAt: Date.now(),
      latestEdl: updated,
    }));
  };

  const handleAutoFaceTrack = async () => {
    if (!currentEDL || isAutoTrackingFace) return;
    setIsAutoTrackingFace(true);
    try {
      const updated = await addAutoFaceTrack(currentEDL, mediaUrls);
      setGeneration({ edl: updated as any });
      updateThread(threadId, (t: ChatThread) => ({
        ...t,
        updatedAt: Date.now(),
        latestEdl: updated,
      }));
    } catch (error: any) {
      console.error("Auto face tracking failed:", error);
    } finally {
      setIsAutoTrackingFace(false);
    }
  };

  const handleAddWallText = () => {
    if (!currentEDL) return;
    const updated = addDemoPlanarTextOverlay(currentEDL, "WALL TEXT");
    setGeneration({ edl: updated as any });
    updateThread(threadId, (t: ChatThread) => ({
      ...t,
      updatedAt: Date.now(),
      latestEdl: updated,
    }));
  };

  const handleChatFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const rawFiles = Array.from(e.target.files ?? []);
    if (rawFiles.length === 0) return;
    const added: UploadedFile[] = [];
    for (const file of rawFiles) {
      let type: UploadedFile["type"] = "footage";
      if (file.type.startsWith("audio/")) type = "music";
      else if (file.type.startsWith("image/")) type = "reference";
      const preview =
        file.type.startsWith("video/") || file.type.startsWith("image/")
          ? URL.createObjectURL(file)
          : undefined;
      added.push({ id: crypto.randomUUID(), file, type, preview });
    }
    const updated = [...uploadedFiles, ...added];
    setUploadedFiles(updated);
    handleFilesChange(updated);
    e.target.value = "";
  };

  const handleNew = () => {
    const t = createThread();
    navigate({ to: "/chat/$threadId", params: { threadId: t.id } } as any);
  };

  const handleDelete = (id: string) => {
    deleteThread(id);
    if (id === threadId) {
      const remaining = (threads as ChatThread[]).filter((t) => t.id !== id);
      if (remaining.length > 0) {
        navigate({ to: "/chat/$threadId", params: { threadId: remaining[0].id } } as any);
      } else {
        const t = createThread();
        navigate({ to: "/chat/$threadId", params: { threadId: t.id } } as any);
      }
    }
  };

  return (
    <div className="grid h-screen grid-cols-[260px_1fr] bg-background text-foreground">
      {/* Sidebar */}
      <aside className="flex flex-col border-r border-border bg-sidebar">
        <Link to="/" className="flex items-center gap-2 px-5 py-5 border-b border-sidebar-border">
          <div className="h-2 w-2 rounded-full bg-primary" />
          <span className="text-xs font-medium tracking-[0.3em] uppercase">monet</span>
        </Link>
        <div className="px-3 py-3">
          <Button
            onClick={handleNew}
            className="w-full justify-start gap-2 bg-secondary text-foreground hover:bg-secondary/70"
            size="sm"
          >
            <Plus className="h-4 w-4" /> New conversation
          </Button>
        </div>
        <div className="flex-1 overflow-y-auto px-2 pb-3">
          {threads.map((t: ChatThread) => (
            <div
              key={t.id}
              className={cn(
                "group flex items-center gap-1 rounded-md px-2 py-2 text-sm cursor-pointer",
                t.id === threadId
                  ? "bg-sidebar-accent text-sidebar-accent-foreground"
                  : "text-muted-foreground hover:bg-sidebar-accent/50",
              )}
            >
              <button
                className="flex-1 truncate text-left"
                onClick={() =>
                  navigate({ to: "/chat/$threadId", params: { threadId: t.id } } as any)
                }
              >
                {t.title || "New conversation"}
              </button>
              <button
                onClick={() => handleDelete(t.id)}
                className="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-background/50 transition-opacity"
                aria-label="Delete thread"
              >
                <Trash2 className="h-3.5 w-3.5" />
              </button>
            </div>
          ))}
        </div>
        <div className="border-t border-sidebar-border p-3">
          <a
            href={`/studio?threadId=${encodeURIComponent(threadId)}`}
            className="flex items-center justify-between rounded-md border border-border bg-card px-3 py-2 text-xs text-muted-foreground hover:text-foreground hover:border-primary/50 transition-colors"
          >
            <span className="flex items-center gap-2">
              <Film className="h-3.5 w-3.5" /> Open Studio
            </span>
            <ArrowRight className="h-3.5 w-3.5" />
          </a>
        </div>
      </aside>

      {/* Main content */}
      <main className="flex flex-col h-screen">
        <header className="flex items-center justify-between border-b border-border px-6 py-4 shrink-0">
          <div>
            <div className="text-[10px] tracking-[0.25em] uppercase text-muted-foreground">
              {currentEDL ? "Editing" : "New edit"}
            </div>
            <h1 className="text-base font-medium truncate max-w-md">
              {active?.title || "New conversation"}
            </h1>
          </div>
          <div className="flex items-center gap-3">
            {currentEDL && (
              <button
                onClick={() => setGeneration({ edl: undefined, edlId: undefined, status: "idle" })}
                className="text-xs text-muted-foreground hover:text-foreground tracking-widest uppercase flex items-center gap-1.5 transition-colors"
              >
                New edit
              </button>
            )}
            <a
              href={`/studio?threadId=${encodeURIComponent(threadId)}`}
              className="text-xs text-muted-foreground hover:text-primary tracking-widest uppercase flex items-center gap-1.5"
            >
              Studio <ArrowRight className="h-3 w-3" />
            </a>
          </div>
        </header>

        {/* Split layout: chat + sliding preview */}
        <div className="flex-1 flex overflow-hidden">
          {/* Chat column — full width when no EDL, narrows when preview slides in */}
          <div
            className={cn(
              "flex flex-col min-w-0 border-r border-border transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)]",
              currentEDL ? "w-[55%]" : "w-full"
            )}
          >
            <div ref={scrollRef} className="flex-1 overflow-y-auto">
              <div className="mx-auto max-w-3xl px-6 py-10">
                {active && active.messages.length === 0 && <EmptyChat onTriggerUpload={() => chatFileInputRef.current?.click()} />}
                {active?.messages.map((m: ChatMessage) => (
                  <Message key={m.id} message={m} />
                ))}

                {/* Show thinking panel during generation */}
                {isGenerating && (
                  <div className="mt-6">
                    <InteractiveThinkingPanel
                      thoughts={thinkingThoughts}
                      questions={thinkingQuestions}
                      isThinking={isGenerating}
                      onQuestionAnswer={(id, answer) => {}}
                    />
                  </div>
                )}

                {/* Refinement section — only when EDL exists */}
                {currentEDL && (
                  <div className="mt-6 border-t border-border pt-4">
                    {patchSummary && (
                      <div className="mb-4 rounded-lg bg-primary/5 border border-primary/20 p-3">
                        <div className="flex items-center gap-2 mb-2">
                          <Sparkles className="h-3 w-3 text-primary" />
                          <span className="text-xs font-medium text-primary">Director Patch Applied</span>
                        </div>
                        <p className="text-sm text-foreground/80">{patchSummary}</p>
                        {directorPreviewUrl && (
                          <div className="mt-3 rounded-md overflow-hidden border border-border bg-black aspect-video">
                            <video src={directorPreviewUrl} controls className="w-full h-full" />
                          </div>
                        )}
                      </div>
                    )}

                    <div className="text-xs text-muted-foreground mb-2 tracking-wider uppercase">
                      Refine with Director
                    </div>
                    <div className="flex gap-2 flex-wrap mb-2">
                      {["Faster cuts", "Hit the drop harder", "More energy", "Calmer pace", "Add glow effect"].map((chip) => (
                        <button
                          key={chip}
                          onClick={() => setRefineFeedback(chip)}
                          className="rounded-full border border-border/60 px-3 py-1 text-xs text-muted-foreground hover:border-primary/50 hover:text-primary transition-colors"
                        >
                          {chip}
                        </button>
                      ))}
                    </div>
                    {annotations.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mb-2">
                        {annotations.map((a) => (
                          <span
                            key={a.id}
                            className="inline-flex items-center gap-1 rounded-full bg-amber-500/10 border border-amber-500/30 px-2 py-0.5 text-xs text-amber-600 dark:text-amber-400"
                          >
                            <StickyNote className="h-2.5 w-2.5 shrink-0" />
                            <span className="font-mono">{Math.floor(a.timestamp / 60)}:{String(Math.floor(a.timestamp % 60)).padStart(2, "0")}</span>
                            <span className="max-w-[120px] truncate">{a.text}</span>
                            <button
                              onClick={() => setAnnotations((prev) => prev.filter((x) => x.id !== a.id))}
                              className="ml-0.5 text-amber-500/60 hover:text-amber-500 transition-colors"
                            >
                              ×
                            </button>
                          </span>
                        ))}
                      </div>
                    )}
                    <div className="flex gap-2">
                      <Textarea
                        value={refineFeedback}
                        onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setRefineFeedback(e.target.value)}
                        placeholder={annotations.length > 0 ? `${annotations.length} annotation${annotations.length !== 1 ? "s" : ""} queued — add global feedback or just hit Apply` : "What would you like to change? (e.g. 'make it more intense')"}
                        className="min-h-[56px] resize-none bg-background border-border text-sm"
                        disabled={isRefining}
                        onKeyDown={(e: React.KeyboardEvent<HTMLTextAreaElement>) => {
                          if (e.key === "Enter" && !e.shiftKey) {
                            e.preventDefault();
                            handleRefine();
                          }
                        }}
                      />
                      <Button
                        size="sm"
                        onClick={handleRefine}
                        disabled={(!refineFeedback.trim() && annotations.length === 0) || isRefining}
                        className="self-end h-9 bg-primary text-primary-foreground hover:bg-primary/90"
                      >
                        {isRefining ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Input area */}
            <div className="border-t border-border bg-background shrink-0">
              <div className="mx-auto max-w-3xl px-6 py-4 space-y-4">
                <VideoUploader
                  key={threadId}
                  onFilesChange={handleFilesChange}
                  onYouTubeUrl={handleYouTubeUrl}
                  disabled={isGenerating}
                />

                {isAnalyzingReference && (
                  <div className="rounded-lg border border-border bg-card px-4 py-3 flex items-center gap-2 text-xs text-muted-foreground">
                    <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    Analyzing reference style…
                  </div>
                )}
                {referenceStyle && !isAnalyzingReference && (
                  <div className="rounded-lg border border-primary/30 bg-primary/5 px-4 py-3 flex items-start justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="text-xs font-medium text-primary mb-1 flex items-center gap-1.5">
                        <Sparkles className="h-3 w-3" />
                        Style reference loaded
                      </div>
                      <div className="text-xs text-muted-foreground mb-1 capitalize">
                        {(referenceStyle.intentMapping.genre ?? "unknown").replace(/_/g, " ")} · {referenceStyle.intentMapping.pacing ?? "unknown"} · {(referenceStyle.rhythm?.avgShotDuration ?? 0).toFixed(1)}s avg shot · {referenceStyle.rhythm?.cutAlignment ?? "unknown"} sync
                      </div>
                    </div>
                    <button
                      onClick={() => {
                        const project = useProjectStore.getState().project;
                        if (project) {
                          useProjectStore.setState({
                            project: { ...project, settings: { ...project.settings, monet: { ...(project.settings?.monet || {}), referenceStyle: undefined, referenceStyleId: undefined } } }
                          });
                        }
                        updateThread(threadId, (t: ChatThread) => ({ ...t, updatedAt: Date.now(), latestReferenceStyle: undefined }));
                      }}
                      className="shrink-0 text-muted-foreground/50 hover:text-muted-foreground transition-colors text-lg leading-none mt-0.5"
                      aria-label="Dismiss reference style"
                    >
                      ×
                    </button>
                  </div>
                )}

                <div className="flex items-center gap-3 px-1">
                  <span className="text-xs text-muted-foreground whitespace-nowrap">Intensity</span>
                  <input
                    type="range"
                    min={0}
                    max={1}
                    step={0.05}
                    value={editIntensity}
                    onChange={(e) => setPrompt({ intensity: parseFloat(e.target.value) })}
                    className="flex-1 h-1.5 bg-muted rounded-full appearance-none cursor-pointer accent-primary"
                  />
                  <span className="text-xs text-muted-foreground w-8 text-right font-mono">{Math.round(editIntensity * 100)}%</span>
                </div>

                <div className="flex items-center gap-3 px-1">
                  <span className="text-xs text-muted-foreground whitespace-nowrap">Tempo</span>
                  <select
                    value={tempoMode}
                    onChange={(e) => setPrompt({ tempoMode: e.target.value })}
                    className="flex-1 text-xs bg-muted border border-border rounded-md px-2 py-1.5 focus:outline-none focus:ring-1 focus:ring-primary"
                  >
                    <option value="beat_anticipated">Hype (ramp + hit)</option>
                    <option value="beat_locked">Beat sync</option>
                    <option value="reference_mirror">Match reference</option>
                    <option value="cinematic">Cinematic</option>
                    <option value="narrative">Narrative</option>
                    <option value="chill_vlog">Chill vlog</option>
                  </select>
                </div>

                <div className="relative rounded-xl border border-border bg-card focus-within:border-primary/50 transition-colors">
                  <Textarea
                    ref={taRef}
                    value={draft}
                    onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setDraft(e.target.value)}
                    placeholder="Describe the edit you want…"
                    className="min-h-[80px] resize-none border-0 bg-transparent px-4 py-3 pr-24 focus-visible:ring-0"
                    disabled={isGenerating}
                    onKeyDown={(e: React.KeyboardEvent<HTMLTextAreaElement>) => {
                      if (e.key === "Enter" && !e.shiftKey) {
                        e.preventDefault();
                        sendMessage();
                      }
                    }}
                  />
                  <div className="absolute right-2 bottom-2 flex items-center gap-1">
                    <input
                      ref={chatFileInputRef}
                      type="file"
                      multiple
                      accept="video/*,audio/*,image/*"
                      onChange={handleChatFileSelect}
                      className="hidden"
                    />
                    <Button
                      size="icon"
                      variant="ghost"
                      onClick={() => chatFileInputRef.current?.click()}
                      disabled={isGenerating}
                      className="h-8 w-8 text-muted-foreground hover:text-foreground"
                      title="Attach files"
                    >
                      <Paperclip className="h-4 w-4" />
                    </Button>
                    <Button
                      size="icon"
                      onClick={() => sendMessage()}
                      disabled={!draft.trim() || isGenerating}
                      className="h-8 w-8 bg-primary text-primary-foreground hover:bg-primary/90"
                    >
                      <Send className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                <p className="text-[10px] text-muted-foreground tracking-widest uppercase">
                  {uploadedFiles.length > 0
                    ? `${uploadedFiles.filter(f => f.type === "footage").length} clip${uploadedFiles.filter(f => f.type === "footage").length !== 1 ? "s" : ""}${uploadedFiles.find(f => f.type === "music") ? " + music" : ""}${uploadedFiles.find(f => f.type === "reference") ? " + reference" : ""} ready`
                    : "Upload footage and music to get started"}
                </p>
              </div>
            </div>
          </div>

          {/* Preview panel — slides in when EDL exists */}
          <div
            className={cn(
              "flex flex-col min-w-0 overflow-hidden transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)]",
              currentEDL ? "w-[45%] opacity-100" : "w-0 opacity-0"
            )}
          >
            {currentEDL && (
              <div className="flex flex-col h-full">
                {/* Preview header */}
                <div className="px-4 py-3 border-b border-border bg-background/80 shrink-0">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <span className="text-[11px] font-semibold tracking-[0.08em] uppercase text-text-muted font-mono">Preview</span>
                      <span className="text-text-tertiary">·</span>
                      <span className="text-[10px] text-text-tertiary font-mono">
                        {previewShotCount} shots · {previewDuration.toFixed(1)}s
                      </span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7"
                        onClick={() => useProjectStore.getState().undo()}
                        disabled={!useProjectStore.getState().canUndo()}
                        title="Undo"
                      >
                        <Undo2 className="h-3.5 w-3.5" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7"
                        onClick={() => useProjectStore.getState().redo()}
                        disabled={!useProjectStore.getState().canRedo()}
                        title="Redo"
                      >
                        <Redo2 className="h-3.5 w-3.5" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7"
                        onClick={handleExport}
                        disabled={isExporting}
                        title="Export MP4"
                      >
                        {isExporting ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
                      </Button>
                      <a
                        href={`/studio?threadId=${encodeURIComponent(threadId)}`}
                        className="h-7 w-7 flex items-center justify-center rounded-md hover:bg-muted transition-colors"
                        title="Open in Studio"
                      >
                        <Film className="h-3.5 w-3.5" />
                      </a>
                    </div>
                  </div>
                </div>

                {/* Preview content */}
                <div className="flex-1 overflow-y-auto p-4 space-y-4">
                  {/* Blueprint */}
                  <BlueprintPreview
                    edl={currentEDL as any}
                    creativeDensity={(thinkingData as any).creativeDensity}
                    referenceSimilarity={(thinkingData as any).referenceSimilarity}
                  />

                  {/* Music Analysis (BeatSync) */}
                  {analysisData?.music && (
                    <AnalysisPanel analysis={analysisData.music} />
                  )}

                  {/* Creative Brief */}
                  {creativeBrief && (
                    <CreativeBriefPanel brief={creativeBrief} />
                  )}

                  {/* Video player */}
                  {previewReady ? (
                    <VideoPreview
                      edl={currentEDL}
                      mediaUrls={mediaUrls}
                      compositionHtml={ENABLE_HYPERFRAMES ? (compositionHtml ?? undefined) : undefined}
                      onAnnotation={(a: TimelineAnnotation) => setAnnotations((prev) => [...prev, a])}
                      annotations={annotations}
                      onTimeUpdate={setPreviewTimeMs}
                      seekToMs={seekToMs}
                      playing={false}
                    />
                  ) : (
                    <div className="rounded-lg border border-border bg-secondary/20 p-4">
                      <p className="text-sm font-medium">Timeline restored</p>
                      <p className="text-xs text-muted-foreground mt-1">
                        Re-upload source clips to bring back the player.
                      </p>
                      {missingPreviewClips.length > 0 && (
                        <div className="flex flex-wrap gap-2 mt-3">
                          {missingPreviewClips.slice(0, 4).map((clipId: string) => (
                            <span key={clipId} className="rounded-full border border-border bg-background px-2.5 py-1 text-[11px] text-muted-foreground">
                              {clipId}
                            </span>
                          ))}
                          {missingPreviewClips.length > 4 && (
                            <span className="rounded-full border border-border bg-background px-2.5 py-1 text-[11px] text-muted-foreground">
                              +{missingPreviewClips.length - 4} more
                            </span>
                          )}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Action buttons */}
                  <div className="flex items-center gap-2 flex-wrap">
                    <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={handleAddTrackedText} disabled={!currentEDL}>
                      Tracked Text
                    </Button>
                    <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={handleAutoFaceTrack} disabled={!currentEDL || isAutoTrackingFace}>
                      {isAutoTrackingFace ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> Tracking…</> : "Face Track"}
                    </Button>
                    <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={handleAddWallText} disabled={!currentEDL}>
                      Wall Text
                    </Button>
                    <Button variant="outline" size="sm" className="gap-1.5 text-xs" onClick={handleExport} disabled={isExporting}>
                      {isExporting ? <><Loader2 className="h-3.5 w-3.5 animate-spin" /> {exportProgress?.percent ?? 0}%</> : <><Download className="h-3.5 w-3.5" /> Export</>}
                    </Button>
                  </div>

                  {/* Text Timeline */}
                  {showTextTimeline && transcript && (
                    <TextTimeline
                      transcript={transcript}
                      edl={currentEDL}
                      currentTimeMs={previewTimeMs}
                      onEDLChange={(updated: MonetEDL) => {
                        setGeneration({ edl: updated as any });
                        updateThread(threadId, (t: ChatThread) => ({ ...t, latestEdl: updated, updatedAt: Date.now() }));
                      }}
                      onSeek={(ms: number) => setSeekToMs(ms)}
                    />
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}

function Message({ message }: { message: ChatMessage }) {
  if (message.role === "user") {
    return (
      <div className="flex justify-end mb-6">
        <div className="max-w-[80%] rounded-2xl bg-primary px-4 py-2.5 text-primary-foreground text-sm leading-relaxed space-y-2">
          <div>{message.content}</div>
          {message.attachments && message.attachments.length > 0 && (
            <div className="flex flex-wrap gap-1.5 pt-1">
              {message.attachments.map((attachment: ChatAttachment) => (
                <span
                  key={`${attachment.id}-${attachment.name}`}
                  className="inline-flex items-center gap-1 rounded-full border border-primary-foreground/30 bg-primary-foreground/10 px-2 py-0.5 text-[11px] text-primary-foreground/90"
                  title={`${attachment.type} · ${formatSize(attachment.sizeBytes)}`}
                >
                  <Paperclip className="h-3 w-3 shrink-0" />
                  <span className="max-w-[200px] truncate">{attachment.name}</span>
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  }
  return (
    <div className="flex gap-3 mb-8">
      <div className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-secondary text-primary">
        <Sparkles className="h-3.5 w-3.5" />
      </div>
      <div className="flex-1 text-sm leading-relaxed whitespace-pre-wrap text-foreground">
        {message.content}
      </div>
    </div>
  );
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function EmptyChat({ onTriggerUpload }: { onTriggerUpload?: () => void }) {
  return (
    <div className="flex flex-col items-center text-center pt-20 pb-10 gap-4">
      <div className="flex h-12 w-12 items-center justify-center rounded-full bg-secondary text-primary">
        <Sparkles className="h-5 w-5" />
      </div>
      <h2 className="text-2xl font-serif">What should we edit?</h2>
      <p className="max-w-md text-sm text-muted-foreground leading-relaxed">
        Drop a clip and tell Monet the vibe. Anime, sports, fan edits — anything goes.
      </p>
      <button
        onClick={onTriggerUpload}
        className="mt-2 flex items-center gap-2 rounded-lg border border-dashed border-primary/40 bg-primary/5 px-5 py-3 text-sm text-primary hover:bg-primary/10 transition-colors"
      >
        <Upload className="h-4 w-4" />
        Upload footage, music, or reference
      </button>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-2 pt-4 w-full max-w-2xl">
        {[
          "Make a 30s hype reel from this match",
          "Anime AMV cut to this song",
          "Color-grade this like Wong Kar-wai",
        ].map((s) => (
          <div
            key={s}
            className="rounded-lg border border-border bg-card px-3 py-2.5 text-xs text-muted-foreground text-left hover:border-primary/50 hover:text-foreground cursor-pointer transition-colors"
          >
            {s}
          </div>
        ))}
      </div>
    </div>
  );
}

