import { createFileRoute } from "@tanstack/react-router";
import { useState, useCallback, useEffect } from "react";

// @ts-expect-error - Route tree auto-generated by TanStack Router; regenerated on dev start
export const Route = createFileRoute("/pricing")({
  component: PricingPage,
});

const PLANS = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "forever",
    description: "Try the AI director, get hooked",
    features: [
      "5 edits per month",
      "720p export",
      "Chat UI only",
      "1 reference video",
      "Basic AI effects",
      "Watermarked exports",
    ],
    cta: "Get Started",
    highlighted: false,
    paddlePriceId: null,
  },
  {
    id: "flux",
    name: "Flux",
    price: "$29",
    period: "/mo",
    description: "For creators who post regularly",
    features: [
      "50 edits per month",
      "1080p export",
      "Kove Advanced (full NLE)",
      "Reference style cloning",
      "Unlimited reference videos",
      "Conversational refinement",
      "No watermark",
      "Priority rendering",
    ],
    cta: "Start Free Trial",
    highlighted: true,
    paddlePriceId: "flux_monthly_29",
  },
  {
    id: "nova",
    name: "Nova",
    price: "$49",
    period: "/mo",
    description: "For serious editors",
    features: [
      "150 edits per month",
      "1080p export (higher bitrate)",
      "Everything in Flux",
      "Multi-reference blending",
      "Batch editing",
      "Custom AI training",
      "Dedicated support",
    ],
    cta: "Start Free Trial",
    highlighted: false,
    paddlePriceId: "nova_monthly_49",
  },
];

function PricingPage() {
  const [loading, setLoading] = useState(false);
  const [userTier, setUserTier] = useState<string | null>(null);
  const [paddleLoaded, setPaddleLoaded] = useState(false);

  useEffect(() => {
    // Check current user tier
    fetch("/api/billing/usage")
      .then((r) => r.json())
      .then((data: any) => {
        if (data.tier) setUserTier(data.tier);
      })
      .catch(() => {});
  }, []);

  useEffect(() => {
    // Load Paddle.js script
    const script = document.createElement("script");
    script.src = "https://cdn.paddle.com/paddle/v2/paddle.js";
    script.async = true;
    script.onload = () => {
      const paddleEnv = import.meta.env.VITE_PADDLE_ENV || "sandbox";
      const paddleToken = import.meta.env.VITE_PADDLE_CLIENT_TOKEN;
      if (window.Paddle && paddleToken) {
        window.Paddle.Environment.set(paddleEnv);
        window.Paddle.Setup({ vendor: Number(paddleToken) });
        setPaddleLoaded(true);
      }
    };
    document.head.appendChild(script);

    return () => {
      document.head.removeChild(script);
    };
  }, []);

  const handleCheckout = useCallback(
    async (priceId: string | null) => {
      if (!priceId) return;
      setLoading(true);

      try {
        const resp = await fetch("/api/billing/checkout", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ priceId }),
        });

        const data = (await resp.json()) as {
          success: boolean;
          transactionId?: string;
          error?: string;
        };

        if (!data.success) {
          alert(data.error || "Failed to create checkout session");
          setLoading(false);
          return;
        }

        // Open Paddle overlay checkout
        if (window.Paddle && data.transactionId) {
          window.Paddle.Checkout.open({
            transactionId: data.transactionId,
          });
        } else {
          alert("Paddle checkout not available. Please try again.");
        }
      } catch (err) {
        console.error("Checkout error:", err);
        alert("An error occurred. Please try again.");
      } finally {
        setLoading(false);
      }
    },
    [],
  );

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      {/* Header */}
      <div className="max-w-4xl mx-auto px-6 pt-16 pb-8 text-center">
        <h1 className="text-4xl font-bold mb-4">Simple, transparent pricing</h1>
        <p className="text-zinc-400 text-lg">
          Start free. Upgrade when you need more power.
        </p>
      </div>

      {/* Plans */}
      <div className="max-w-4xl mx-auto px-6 pb-24">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {PLANS.map((plan) => (
            <div
              key={plan.id}
              className={`relative rounded-2xl p-8 ${
                plan.highlighted
                  ? "bg-gradient-to-b from-orange-500/10 to-transparent border border-orange-500/30"
                  : "bg-zinc-900/50 border border-zinc-800"
              }`}
            >
              {plan.highlighted && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 bg-orange-500 text-white text-xs font-semibold rounded-full">
                  Most Popular
                </div>
              )}

              <h2 className="text-xl font-semibold mb-2">{plan.name}</h2>
              <div className="flex items-baseline gap-1 mb-4">
                <span className="text-4xl font-bold">{plan.price}</span>
                <span className="text-zinc-500">{plan.period}</span>
              </div>
              <p className="text-zinc-400 text-sm mb-6">{plan.description}</p>

              <button
                onClick={() => handleCheckout(plan.paddlePriceId)}
                disabled={loading || userTier === plan.id}
                className={`w-full py-3 px-4 rounded-lg font-medium text-sm transition-all ${
                  plan.highlighted
                    ? "bg-orange-500 hover:bg-orange-600 text-white"
                    : "bg-zinc-800 hover:bg-zinc-700 text-zinc-200"
                } ${
                  (loading || userTier === plan.id)
                    ? "opacity-50 cursor-not-allowed"
                    : "cursor-pointer"
                }`}
              >
                {userTier === plan.id
                  ? "Current Plan"
                  : plan.cta}
              </button>

              <ul className="mt-8 space-y-3">
                {plan.features.map((feature) => (
                  <li key={feature} className="flex items-center gap-3 text-sm text-zinc-300">
                    <svg
                      className={`w-4 h-4 flex-shrink-0 ${
                        plan.highlighted ? "text-orange-400" : "text-zinc-500"
                      }`}
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                    {feature}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* FAQ */}
        <div className="mt-16 max-w-2xl mx-auto">
          <h2 className="text-2xl font-semibold text-center mb-8">Frequently asked questions</h2>
          <div className="space-y-6">
            {[
              {
                q: "What counts as an edit?",
                a: "Each time you generate or refine an EDL counts as one edit. Previewing and browsing don't count.",
              },
              {
                q: "Can I switch between plans?",
                a: "Yes. Upgrade anytime and your new features activate immediately. Downgrade takes effect at the end of your billing period.",
              },
              {
                q: "Do you handle taxes?",
                a: "Yes. Paddle is our Merchant of Record — they handle all taxes, compliance, and payment processing globally.",
              },
              {
                q: "Is there a free trial?",
                a: "Your first month on any paid plan is a full-featured trial. Cancel anytime before the period ends and you won't be charged.",
              },
            ].map((faq) => (
              <div key={faq.q}>
                <h3 className="font-medium mb-1">{faq.q}</h3>
                <p className="text-sm text-zinc-400">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Affiliate Program */}
        <div className="mt-16 max-w-2xl mx-auto text-center">
          <h2 className="text-2xl font-semibold mb-4">Affiliate Program</h2>
          <p className="text-zinc-400 text-sm mb-6">
            Earn by sharing Kove. Get paid for every subscriber you refer.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-lg mx-auto">
            <div className="rounded-xl bg-zinc-900/50 border border-zinc-800 p-6">
              <div className="text-2xl font-bold text-orange-400 mb-1">30%</div>
              <div className="text-sm text-zinc-400">One-time commission</div>
              <div className="text-xs text-zinc-500 mt-2">Per new subscriber you refer</div>
            </div>
            <div className="rounded-xl bg-zinc-900/50 border border-zinc-800 p-6">
              <div className="text-2xl font-bold text-orange-400 mb-1">15%</div>
              <div className="text-sm text-zinc-400">Monthly recurring</div>
              <div className="text-xs text-zinc-500 mt-2">Ongoing while they stay subscribed</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Extend Window for Paddle.js global
declare global {
  interface Window {
    Paddle?: {
      Environment: { set: (env: string) => void };
      Setup: (config: { vendor: number }) => void;
      Checkout: { open: (config: { transactionId: string }) => void };
    };
  }
}
