import { SignUp } from "@clerk/react";
import { createFileRoute } from "@tanstack/react-router";

// @ts-expect-error - Route tree auto-generated by TanStack Router; regenerated on dev start
export const Route = createFileRoute("/sign-up/$")({
  component: SignUpPage,
});

function SignUpPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-black">
      <SignUp />
    </div>
  );
}
