import { SignIn } from "@clerk/react";
import { createFileRoute } from "@tanstack/react-router";

// @ts-expect-error - Route tree auto-generated by TanStack Router; regenerated on dev start
export const Route = createFileRoute("/sign-in/$")({
  component: SignInPage,
});

function SignInPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-black">
      <SignIn />
    </div>
  );
}
