import { useEffect } from "react";
import { SignUp, useUser } from "@clerk/react";
import { createFileRoute } from "@tanstack/react-router";

// @ts-expect-error - Route tree auto-generated by TanStack Router; regenerated on dev start
export const Route = createFileRoute("/sign-up/$")({
  component: SignUpPage,
});

function ReferralTracker() {
  const { user, isSignedIn } = useUser();

  useEffect(() => {
    if (!isSignedIn || !user) return;

    const cookies = document.cookie.split(";").map((c) => c.trim());
    const refCookie = cookies.find((c) => c.startsWith("kove_ref="));
    if (!refCookie) return;

    const code = decodeURIComponent(refCookie.split("=")[1]);
    if (!code) return;

    fetch("/api/affiliate/track-referral", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ code, newUserId: user.id }),
    }).then(() => {
      document.cookie = "kove_ref=;path=/;max-age=0";
    }).catch(() => {});
  }, [isSignedIn, user]);

  return null;
}

function SignUpPage() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-black">
      <ReferralTracker />
      <SignUp />
    </div>
  );
}
