/**
 * CompositionOverlay
 *
 * Renders a HyperFrames-compatible HTML composition in a transparent iframe
 * synced to the video player's current time.
 *
 * The iframe is positioned absolutely over the parent container with
 * pointer-events: none so it never intercepts video scrubbing.
 *
 * Parent → iframe comms:
 *   postMessage({ type: 'hf-seek', time: number })
 */

import { useEffect, useRef, useState } from "react";

interface CompositionOverlayProps {
  /** Self-contained HTML string (generated by composition-generator.ts) */
  html: string;
  /** Current playback position in seconds — triggers timeline seek */
  currentTime: number;
  /** When false, the overlay is hidden (e.g., while loading) */
  visible?: boolean;
}

export function CompositionOverlay({ html, currentTime, visible = true }: CompositionOverlayProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [blobUrl, setBlobUrl] = useState<string | null>(null);
  const [ready, setReady] = useState(false);
  const lastTimeRef = useRef<number>(-1);

  // Build a blob URL from the HTML string
  useEffect(() => {
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    setBlobUrl(url);
    setReady(false); // iframe must reload
    return () => URL.revokeObjectURL(url);
  }, [html]);

  // Mark ready once iframe has loaded
  const handleLoad = () => setReady(true);

  // Seek the GSAP timeline whenever currentTime changes
  useEffect(() => {
    if (!ready || !iframeRef.current?.contentWindow) return;
    if (Math.abs(currentTime - lastTimeRef.current) < 0.016) return; // ~1 frame
    lastTimeRef.current = currentTime;
    iframeRef.current.contentWindow.postMessage(
      { type: "hf-seek", time: currentTime },
      "*"
    );
  }, [currentTime, ready]);

  if (!blobUrl) return null;

  return (
    <iframe
      ref={iframeRef}
      src={blobUrl}
      onLoad={handleLoad}
      title="monet-composition-overlay"
      style={{
        position: "absolute",
        inset: 0,
        width: "100%",
        height: "100%",
        border: "none",
        pointerEvents: "none",
        background: "transparent",
        opacity: visible && ready ? 1 : 0,
        transition: "opacity 0.2s ease",
      }}
      // allow scripts but keep it sandboxed from parent DOM
      // allow-same-origin needed for blob URL CSP compliance
      sandbox="allow-scripts allow-same-origin"
    />
  );
}
