// src/server/lib/ass-text-generator.ts
// Converts raw timestamped word strings into Advanced SubStation Alpha (.ass) format.
// Supports animated text overlay tags: {\move}, {\fscx}, {\fad}, {\pos}, {\an}.
// Based on ASS animation keyframe approach (JestAK/ass-animation).

export interface ASSTextEntry {
  /** The text to display. */
  text: string;
  /** Start time in seconds. */
  startTime: number;
  /** End time in seconds. */
  endTime: number;
  /** Horizontal position (0-1, 0.5 = center). */
  x?: number;
  /** Vertical position (0-1, 0.5 = center). */
  y?: number;
  /** Font size override. */
  fontSize?: number;
  /** Font color as hex (e.g., "#FFFFFF" or "&H00FFFFFF"). */
  color?: string;
  /** Bold text. */
  bold?: boolean;
  /** Outline/stroke width (0 = no outline). */
  outline?: number;
  /** Shadow depth (0 = no shadow). */
  shadow?: number;
  /** Fade-in duration in seconds. */
  fadeIn?: number;
  /** Fade-out duration in seconds. */
  fadeOut?: number;
  /** Move animation: target x,y position (0-1 normalized). */
  moveTo?: { x: number; y: number };
  /** Scale animation: target X scale percentage (100 = normal). */
  scaleX?: number;
  /** Scale animation: target Y scale percentage (100 = normal). */
  scaleY?: number;
}

export interface ASSGenerateOptions {
  /** Video resolution width (default 1920). */
  width?: number;
  /** Video resolution height (default 1080). */
  height?: number;
  /** Default font name (default "Arial"). */
  fontName?: string;
  /** Default font size (default 48). */
  fontSize?: number;
  /** Default font color (default "&H00FFFFFF" = white). */
  fontColor?: string;
  /** Default outline color (default "&H00000000" = black). */
  outlineColor?: string;
  /** Default outline width (default 2). */
  outlineWidth?: number;
}

/**
 * Generate a complete .ass subtitle file from timestamped text entries.
 *
 * @param entries - Array of text entries with timing and optional styling
 * @param options - Video resolution and default style options
 * @returns The complete .ass file content as a string
 */
export function generateASSFile(
  entries: ASSTextEntry[],
  options: ASSGenerateOptions = {},
): string {
  const {
    width = 1920,
    height = 1080,
    fontName = "Arial",
    fontSize = 48,
    fontColor = "&H00FFFFFF",
    outlineColor = "&H00000000",
    outlineWidth = 2,
  } = options;

  const scriptInfo = buildScriptInfo(width, height);
  const styles = buildStyles(fontName, fontSize, fontColor, outlineColor, outlineWidth);
  const dialogueLines = entries.map((entry) =>
    buildDialogueLine(entry, width, height),
  );

  return [
    scriptInfo,
    styles,
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ...dialogueLines,
    "",
  ].join("\n");
}

/**
 * Convert raw timestamped word strings into .ass format.
 *
 * Input format: Array of { word, start, end } objects
 * Output: Complete .ass file content with animated text
 */
export function wordsToASS(
  words: Array<{ word: string; start: number; end: number }>,
  options: ASSGenerateOptions = {},
): string {
  const entries: ASSTextEntry[] = words.map((w) => ({
    text: w.word,
    startTime: w.start,
    endTime: w.end,
    fadeIn: 0.05,
    fadeOut: 0.05,
  }));

  return generateASSFile(entries, options);
}

// ─── INTERNAL BUILDERS ────────────────────────────────────────────

function buildScriptInfo(width: number, height: number): string {
  return [
    "[Script Info]",
    "; Generated by Monet AI Video Editor",
    "ScriptType: v4.00+",
    `PlayResX: ${width}`,
    `PlayResY: ${height}`,
    "Timer: 100.0000",
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "YCbCr Matrix: TV.709",
    "",
  ].join("\n");
}

function buildStyles(
  fontName: string,
  fontSize: number,
  fontColor: string,
  outlineColor: string,
  outlineWidth: number,
): string {
  return [
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Default,${fontName},${fontSize},${fontColor},&H000000FF,${outlineColor},&H80000000,-1,0,0,0,100,100,0,0,1,${outlineWidth},1,2,10,10,10,1`,
    `Style: Bold,${fontName},${fontSize + 4},${fontColor},&H000000FF,${outlineColor},&H80000000,-1,0,0,0,100,100,0,0,1,${outlineWidth + 1},2,2,10,10,10,1`,
    `Style: Center,${fontName},${fontSize},${fontColor},&H000000FF,${outlineColor},&H80000000,-1,0,0,0,100,100,0,0,1,${outlineWidth},1,5,10,10,10,1`,
    `Style: Title,${fontName},${fontSize * 2},${fontColor},&H000000FF,${outlineColor},&H80000000,-1,0,0,0,100,100,0,0,1,${outlineWidth + 2},2,5,10,10,10,1`,
    "",
  ].join("\n");
}

function buildDialogueLine(
  entry: ASSTextEntry,
  width: number,
  height: number,
): string {
  const start = formatASSTime(entry.startTime);
  const end = formatASSTime(entry.endTime);
  const style = entry.bold ? "Bold" : "Default";
  const name = "";

  // Build inline override tags
  const tags: string[] = [];

  // Position tag
  const posX = entry.x !== undefined ? Math.round(entry.x * width) : Math.round(width * 0.5);
  const posY = entry.y !== undefined ? Math.round(entry.y * height) : Math.round(height * 0.9);
  tags.push(`{\\pos(${posX},${posY})}`);

  // Fade tag: {\fad(fadeInMs,fadeOutMs)}
  if (entry.fadeIn !== undefined || entry.fadeOut !== undefined) {
    const fadeInMs = Math.round((entry.fadeIn ?? 0) * 1000);
    const fadeOutMs = Math.round((entry.fadeOut ?? 0) * 1000);
    tags.push(`{\\fad(${fadeInMs},${fadeOutMs})}`);
  }

  // Move tag: {\move(fromX,fromY,toX,toY,time1,time2)}
  if (entry.moveTo) {
    const fromX = Math.round(posX);
    const fromY = Math.round(posY);
    const toX = Math.round(entry.moveTo.x * width);
    const toY = Math.round(entry.moveTo.y * height);
    tags.push(`{\\move(${fromX},${fromY},${toX},${toY})}`);
  }

  // Scale tags: {\fscx(100)}{\fscy(100)}
  if (entry.scaleX !== undefined) {
    tags.push(`{\\fscx(${Math.round(entry.scaleX)})}`);
  }
  if (entry.scaleY !== undefined) {
    tags.push(`{\\fscy(${Math.round(entry.scaleY)})}`);
  }

  // Font size override
  if (entry.fontSize !== undefined) {
    tags.push(`{\\fs${entry.fontSize}}`);
  }

  // Color override: ASS uses &HAABBGGRR format
  if (entry.color) {
    const assColor = hexToASSColor(entry.color);
    tags.push(`{\\c${assColor}}`);
  }

  // Outline override
  if (entry.outline !== undefined) {
    tags.push(`{\\ bord${entry.outline}}`);
  }

  // Shadow override
  if (entry.shadow !== undefined) {
    tags.push(`{\\shad${entry.shadow}}`);
  }

  // Alignment override
  if (entry.y !== undefined && entry.y < 0.3) {
    tags.push("{\\an8}"); // Top-center
  } else if (entry.y !== undefined && entry.y > 0.7) {
    tags.push("{\\an2}"); // Bottom-center
  }

  // Escape text for ASS (special chars)
  const escapedText = escapeASSText(entry.text);

  return `Dialogue: 0,${start},${end},${style},${name},0,0,0,,${tags.join("")}${escapedText}`;
}

/**
 * Format seconds to ASS time format: H:MM:SS.cc
 */
function formatASSTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const cs = Math.floor((seconds % 1) * 100);
  return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}.${String(cs).padStart(2, "0")}`;
}

/**
 * Convert hex color to ASS &H00BBGGRR format.
 */
function hexToASSColor(hex: string): string {
  const clean = hex.replace("#", "");
  if (clean.length === 6) {
    const r = clean.substring(0, 2);
    const g = clean.substring(2, 4);
    const b = clean.substring(4, 6);
    return `&H00${b}${g}${r}`;
  }
  return hex; // Already in ASS format
}

/**
 * Escape special characters for ASS subtitle format.
 */
function escapeASSText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}");
}

/**
 * Generate an ASS file optimized for word-by-word subtitle highlighting.
 * Each word gets its own dialogue line with precise timing for karaoke-style display.
 */
export function generateWordHighlightASS(
  words: Array<{ word: string; start: number; end: number }>,
  options: ASSGenerateOptions = {},
): string {
  const {
    width = 1920,
    height = 1080,
    fontName = "Arial",
    fontSize = 48,
    fontColor = "&H00FFFFFF",
    outlineColor = "&H00000000",
    outlineWidth = 2,
  } = options;

  const scriptInfo = buildScriptInfo(width, height);

  const styles = [
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    `Style: Default,${fontName},${fontSize},${fontColor},&H000000FF,${outlineColor},&H80000000,-1,0,0,0,100,100,0,0,1,${outlineWidth},1,2,10,10,10,1`,
    `Style: Highlight,${fontName},${fontSize},&H0000FFFF,&H000000FF,${outlineColor},&H80000000,-1,0,0,0,100,100,0,0,1,${outlineWidth + 1},2,2,10,10,10,1`,
    "",
  ].join("\n");

  // Group words into lines (every ~6 words or on natural breaks)
  const lines: typeof words[] = [];
  let currentLine: typeof words = [];
  for (const w of words) {
    currentLine.push(w);
    if (currentLine.length >= 6 || w.word.endsWith(".") || w.word.endsWith(",") || w.word.endsWith("?")) {
      lines.push(currentLine);
      currentLine = [];
    }
  }
  if (currentLine.length > 0) lines.push(currentLine);

  // Build dialogue: one line per word group
  const dialogueLines: string[] = [];
  for (const lineWords of lines) {
    const lineStart = lineWords[0].start;
    const lineEnd = lineWords[lineWords.length - 1].end;

    // Build the full line text
    const fullText = lineWords.map((w) => w.word).join(" ");

    // Add fade-in for the line
    const start = formatASSTime(lineStart);
    const end = formatASSTime(lineEnd);

    dialogueLines.push(
      `Dialogue: 0,${start},${end},Default,,0,0,0,,{\\fad(50,50)}${fullText}`,
    );
  }

  return [
    scriptInfo,
    styles,
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ...dialogueLines,
    "",
  ].join("\n");
}
