/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleLabRouteImport } from './routes/style-lab'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SimpleEditorRouteImport } from './routes/simple-editor'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ExperimentalRouteImport } from './routes/experimental'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioProjectIdRouteImport } from './routes/studio_.$projectId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ChatThreadIdRouteImport } from './routes/chat_.$threadId'

const StyleLabRoute = StyleLabRouteImport.update({
  id: '/style-lab',
  path: '/style-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleEditorRoute = SimpleEditorRouteImport.update({
  id: '/simple-editor',
  path: '/simple-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentalRoute = ExperimentalRouteImport.update({
  id: '/experimental',
  path: '/experimental',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioProjectIdRoute = StudioProjectIdRouteImport.update({
  id: '/studio_/$projectId',
  path: '/studio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat_/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/experimental': typeof ExperimentalRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/simple-editor': typeof SimpleEditorRoute
  '/studio': typeof StudioRoute
  '/style-lab': typeof StyleLabRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/r/$code': typeof RCodeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/experimental': typeof ExperimentalRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/simple-editor': typeof SimpleEditorRoute
  '/studio': typeof StudioRoute
  '/style-lab': typeof StyleLabRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/r/$code': typeof RCodeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/studio/$projectId': typeof StudioProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/experimental': typeof ExperimentalRoute
  '/landing': typeof LandingRoute
  '/pricing': typeof PricingRoute
  '/simple-editor': typeof SimpleEditorRoute
  '/studio': typeof StudioRoute
  '/style-lab': typeof StyleLabRoute
  '/chat_/$threadId': typeof ChatThreadIdRoute
  '/r/$code': typeof RCodeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/studio_/$projectId': typeof StudioProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/editor'
    | '/experimental'
    | '/landing'
    | '/pricing'
    | '/simple-editor'
    | '/studio'
    | '/style-lab'
    | '/chat/$threadId'
    | '/r/$code'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/studio/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/editor'
    | '/experimental'
    | '/landing'
    | '/pricing'
    | '/simple-editor'
    | '/studio'
    | '/style-lab'
    | '/chat/$threadId'
    | '/r/$code'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/studio/$projectId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/editor'
    | '/experimental'
    | '/landing'
    | '/pricing'
    | '/simple-editor'
    | '/studio'
    | '/style-lab'
    | '/chat_/$threadId'
    | '/r/$code'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/studio_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  ExperimentalRoute: typeof ExperimentalRoute
  LandingRoute: typeof LandingRoute
  PricingRoute: typeof PricingRoute
  SimpleEditorRoute: typeof SimpleEditorRoute
  StudioRoute: typeof StudioRoute
  StyleLabRoute: typeof StyleLabRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  RCodeRoute: typeof RCodeRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  StudioProjectIdRoute: typeof StudioProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-lab': {
      id: '/style-lab'
      path: '/style-lab'
      fullPath: '/style-lab'
      preLoaderRoute: typeof StyleLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple-editor': {
      id: '/simple-editor'
      path: '/simple-editor'
      fullPath: '/simple-editor'
      preLoaderRoute: typeof SimpleEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experimental': {
      id: '/experimental'
      path: '/experimental'
      fullPath: '/experimental'
      preLoaderRoute: typeof ExperimentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio_/$projectId': {
      id: '/studio_/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat_/$threadId': {
      id: '/chat_/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  ExperimentalRoute: ExperimentalRoute,
  LandingRoute: LandingRoute,
  PricingRoute: PricingRoute,
  SimpleEditorRoute: SimpleEditorRoute,
  StudioRoute: StudioRoute,
  StyleLabRoute: StyleLabRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  RCodeRoute: RCodeRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  StudioProjectIdRoute: StudioProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
